# Generated by Django 2.1.8 on 2019-12-04 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.CharField(blank=True, max_length=255, null=True)),
                ('oldauthor', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('authordate', models.CharField(blank=True, max_length=255, null=True)),
                ('inferreddate', models.PositiveIntegerField(blank=True, max_length=255, null=True)),
                ('latestcomp', models.PositiveIntegerField(blank=True, null=True)),
                ('datetype', models.CharField(blank=True, max_length=255, null=True)),
                ('startdate', models.CharField(blank=True, max_length=255, null=True)),
                ('enddate', models.CharField(blank=True, max_length=255, null=True)),
                ('imprint', models.CharField(blank=True, max_length=255, null=True)),
                ('imprintdate', models.CharField(blank=True, max_length=255, null=True)),
                ('contents', models.CharField(blank=True, max_length=255, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('subjects', models.CharField(blank=True, max_length=255, null=True)),
                ('geographics', models.CharField(blank=True, max_length=255, null=True)),
                ('locnum', models.CharField(blank=True, max_length=255, null=True)),
                ('oclc', models.PositiveIntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('recordid', models.PositiveIntegerField(blank=True, null=True)),
                ('enumcron', models.CharField(blank=True, max_length=255, null=True)),
                ('volnum', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('parttitle', models.CharField(blank=True, max_length=255, null=True)),
                ('shorttitle', models.CharField(blank=True, max_length=255, null=True)),
                ('instances', models.PositiveIntegerField(blank=True, null=True)),
                ('juvenileprob', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('nonficprob', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
    ]
