# Generated by Django 2.1.8 on 2019-12-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191205_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
