# Generated by Django 2.1.8 on 2019-12-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191205_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='subjects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
