# Generated by Django 2.1.8 on 2019-12-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191205_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='shorttitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
