# Generated by Django 2.1.8 on 2019-12-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191205_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='genres',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
