# Generated by Django 2.1.8 on 2019-12-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191205_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='imprint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='parttitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
