# Generated by Django 2.1.8 on 2019-12-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191205_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='oclc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
